/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel.gamevisual;

import javax.swing.JLabel;

/**
 *
 * @author siux
 */
public abstract class AbstractPanelGameInfo extends javax.swing.JPanel {

    /**
     * Creates new form AbstractPanelGameInfo
     */
    public AbstractPanelGameInfo() {
        initComponents();
    }
    
    private JLabel lblInfo;
    private JLabel lblDescription;

    public JLabel getLblInfo() {
        return lblInfo;
    }

    public JLabel getLblDescription() {
        return lblDescription;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(2, 1));
    }// </editor-fold>//GEN-END:initComponents

    public void prepareInfo() {
        lblInfo = makeLblInfo();
        lblDescription = makeLblDescription();
        
        add(lblDescription);
        add(lblInfo);
    }

    protected abstract JLabel makeLblInfo();
    protected abstract JLabel makeLblDescription();
    
    public abstract void refreshView();



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
